
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: First job
    steps: 
    - bash: echo Build First Job
  - job: Second job
    steps: 
    - bash: echo Build Second Job  
- stage: QADeploy
  jobs:
  - job: First job
    steps: 
    - bash: echo Build First QADeployJob
  - job: Second job
    steps: 
    - bash: echo Build Second QADeployJob 
- stage: ProdDeploy
  jobs:
  - job: First job
    steps: 
    - bash: echo Build First ProdDeployJob
  - job: Second job
    steps: 
    - bash: echo SK says All steps of All JObs in all Stages are complete



